spring.application.name=vidhvyn

spring.datasource.url=jdbc:mysql://localhost:3306/vidhvyn
spring.datasource.username=root
spring.datasource.password=Venkatesh@0673
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver