spring.application.name=vidhvyn
# ===============================
# DATABASE CONFIG
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/vidhvyn
spring.datasource.username=root
spring.datasource.password=Venkatesh@0673
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
# ===============================
# Default Format
# ===============================
spring.mvc.format.date=yyyy-MM-dd
# ===============================
# Email Service
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=venkateshmoney09@gmail.com
spring.mail.password=eleeymsvfeuuxqav
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
# ===============================
# Captcha
# ===============================
recaptcha.site-key=6LfkN0QsAAAAAJnD4hv9Gm08tTjDllzC607HQioF
recaptcha.secret-key=6LfkN0QsAAAAACMbfpFjixQ9fRv295HHTflVk1fr
recaptcha.verify-url=https://www.google.com/recaptcha/api/siteverify
